### ISSUE TITLE
Not working just error :(

### ISSUE THREAD

**Issue by scriptzteam** [madcowfred/newsmangler#20]
python 2.4.3

Traceback (most recent call last):
  File "mangler.py", line 38, in ?
    from newsmangler.postmangler import PostMangler
  File "/home/newsmangler-master/newsmangler/postmangler.py", line 363
    with open(filename, 'w') as nzbfile:
            ^
SyntaxError: invalid syntax

python 2.6
  File "mangler.py", line 38, in <module>
    from newsmangler.postmangler import PostMangler
  File "/home/newsmangler-master/newsmangler/postmangler.py", line 46, in <module>
    from newsmangler.article import Article
  File "/home/newsmangler-master/newsmangler/article.py", line 28, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict

**Comment by thezoggy** [comment]
2.4.x isnt supported

**Comment by madcowfred** [comment]
Added a workaround for this in 5e6bf8c. Try 'pip install ordereddict' and it should work. If you don't have pip it's generally in some sort of python setuptools package/port/whatever.

**Comment by nickma82** [comment]
close it plz
