### ISSUE TITLE
memory leak when using python-vanilla module

### ISSUE THREAD

**Issue by comfun** [madcowfred/newsmangler#4]
When using python-vanilla module to yencode, I often encounter those kind of errors resulting the posts to fail and sometimes a huge memory leak if the process is not killed . Those errors doesn't occurs when using python-yenc module.

exemples:

Traceback (most recent call last):
  File "/home/animus/scripts/newsmangler/classes/BaseMangler.py", line 88, in poll
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/home/animus/scripts/newsmangler/classes/asyncNNTP.py", line 225, in handle_read
    self.post_data()
  File "/home/animus/scripts/newsmangler/classes/asyncNNTP.py", line 272, in post_data
    data = self._postfile.read(POST_READ_SIZE)

Traceback (most recent call last):/s
  File "/home/animus/scripts/newsmangler/poster.py", line 146, in <module>
    main()
  File "/home/animus/scripts/newsmangler/poster.py", line 141, in main
    generate_par2=options.generate_par2)
  File "/home/animus/scripts/newsmangler/classes/Poster.py", line 119, in post
    self.build_article(postfile, article)
  File "/home/animus/scripts/newsmangler/classes/Poster.py", line 285, in build_article
    partcrc = yEnc.yEncode(postfile, data)
  File "/home/animus/scripts/newsmangler/classes/yEnc.py", line 114, in yEncode_Python
    postfile.write('\r\n')
MemoryError: out of memory

Traceback (most recent call last):
  File "/home/animus/scripts/newsmangler/poster.py", line 146, in <module>
    main()
  File "/home/animus/scripts/newsmangler/poster.py", line 141, in main
    generate_par2=options.generate_par2)
  File "/home/animus/scripts/newsmangler/classes/Poster.py", line 119, in post
    self.build_article(postfile, article)
  File "/home/animus/scripts/newsmangler/classes/Poster.py", line 285, in build_article
    partcrc = yEnc.yEncode(postfile, data)
  File "/home/animus/scripts/newsmangler/classes/yEnc.py", line 81, in yEncode_Python
    translated = data.translate(YENC_TRANS)
MemoryError

**Comment by alok0** [comment]
This is the same issue as issue #2

**Comment by comfun** [comment]
Wasn"t sure about it, but if you say so the ticket can be closed.

By the way I'm using right now python-yenc 0.4 module, https://bitbucket.org/dual75/yenc and it's working like a charm.
