### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'handle_error'

### ISSUE THREAD

**Issue by stasjok** [madcowfred/newsmangler#7]
Hello. Sometimes I get this error. And NZB-file isn't generated. But files seems to be posted OK.

2012-01-19 12:29:19,252 [WARNING] 5: unknown response from server - "400 news.astraweb.com: Idle timeout."
2012-01-19 12:29:19,313 [ERROR] 5: unhandled exception!
Traceback (most recent call last):
  File "/opt/newsmangler/classes/BaseMangler.py", line 88, in poll
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/opt/newsmangler/classes/asyncNNTP.py", line 169, in handle_read
    self._readbuf += self.recv(16384)
  File "/usr/lib64/python2.6/asyncore.py", line 377, in recv
    self.handle_close()
  File "/opt/newsmangler/classes/asyncNNTP.py", line 151, in handle_close
    self.really_close()
  File "/opt/newsmangler/classes/asyncNNTP.py", line 157, in really_close
    self.close()
  File "/opt/newsmangler/classes/asyncNNTP.py", line 99, in close
    self.del_channel()
  File "/opt/newsmangler/classes/asyncNNTP.py", line 94, in del_channel
    asyncore.poller.unregister(self._fileno)
TypeError: argument must be an int, or have a fileno() method.
2012-01-19 12:29:19,355 [WARNING] Invalid FD for poll() - 8
Traceback (most recent call last):
  File "/usr/bin/newsmangler", line 146, in <module>
    main()
  File "/usr/bin/newsmangler", line 141, in main
    generate_par2=options.generate_par2)
  File "/opt/newsmangler/classes/Poster.py", line 113, in post
    _poll()
  File "/opt/newsmangler/classes/BaseMangler.py", line 96, in poll
    obj.handle_error()
AttributeError: 'NoneType' object has no attribute 'handle_error'

**Comment by greencopper** [comment]
Yes, this happens whenever newsmangler gets a timeout due to a lost connection.

**Comment by luw** [comment]
hi i get something similar but I don't believe it is timeout related (maybe though).  any ideas?

2012-01-31 06:23:41,256 [INFO] Using yenc-vanilla module for yEnc encoding.
2012-01-31 06:23:44,611 [ERROR] 0: unhandled exception!
Traceback (most recent call last):
  File "/home/dave/newsmangler/classes/BaseMangler.py", line 88, in poll
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 414, in handle_read_event
    self.handle_read()
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 171, in handle_read
    self.really_close(msg)
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 157, in really_close
    self.close()
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 99, in close
    self.del_channel()
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 94, in del_channel
    asyncore.poller.unregister(self._fileno)
TypeError: argument must be an int, or have a fileno() method.
2012-01-31 06:23:44,624 [WARNING] Invalid FD for poll() - 3
Traceback (most recent call last):
  File "./poster.py", line 146, in <module>
    main()
  File "./poster.py", line 141, in main
    generate_par2=options.generate_par2)
  File "/home/dave/newsmangler/classes/Poster.py", line 90, in post
    _poll()
  File "/home/dave/newsmangler/classes/BaseMangler.py", line 96, in poll
    obj.handle_error()
AttributeError: 'NoneType' object has no attribute 'handle_error'
dave@davemain4:~/newsmangler$ ./poster.py -p --config=sample.conf happyhappypoopface/
\2012-01-31 06:24:31,502 [INFO] Using yenc-vanilla module for yEnc encoding.
2012-01-31 06:24:34,863 [ERROR] 0: unhandled exception!
Traceback (most recent call last):
  File "/home/dave/newsmangler/classes/BaseMangler.py", line 88, in poll
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 414, in handle_read_event
    self.handle_read()
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 171, in handle_read
    self.really_close(msg)
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 157, in really_close
    self.close()
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 99, in close
    self.del_channel()
  File "/home/dave/newsmangler/classes/asyncNNTP.py", line 94, in del_channel
    asyncore.poller.unregister(self._fileno)
TypeError: argument must be an int, or have a fileno() method.
2012-01-31 06:24:34,876 [WARNING] Invalid FD for poll() - 3
Traceback (most recent call last):
  File "./poster.py", line 146, in <module>
    main()
  File "./poster.py", line 141, in main
    generate_par2=options.generate_par2)
  File "/home/dave/newsmangler/classes/Poster.py", line 90, in post
    _poll()
  File "/home/dave/newsmangler/classes/BaseMangler.py", line 96, in poll
    obj.handle_error()
AttributeError: 'NoneType' object has no attribute 'handle_error'

**Comment by outtahere** [comment]
I get this error posting to Thundernews but not Giganews ;) so it's likely relevant to all Highwinds newsservers. 

Let me know if you want to test with thundernews.

btw same error using vanilla or fred yenc.

traceback here: http://pastie.org/3515697

**Comment by madcowfred** [comment]
Can you try updating to current git code and running "python poster.py --debug somedirectory"?

**Comment by outtahere** [comment]
Ok done. Sits on POST for 3 mins until timeout(i guess) then writes traceback.

debug output here: http://pastie.org/3552456

cheers

**Comment by madcowfred** [comment]
The timeout on connect should be fixed as of the last commit, I'll try to track down where connection errors aren't being handled properly for the previous error.

**Comment by madcowfred** [comment]
Connection errors seem to be handled properly now, you might occasionally drop articles but if you're posting with PAR2s it shouldn't realllly be an issue. I'm working on rewriting the article queue disaster next which should eliminate that entirely.

**Comment by madcowfred** [comment]
Assuming this is fixed since nobody has posted in a while.
