### ISSUE TITLE
Poster is stuck trying to send

### ISSUE THREAD

**Issue by Nethecite** [madcowfred/newsmangler#8]
Don't think this is the same issue that alok0 was having.

When trying to post, it gets stuck in some loop, whether it's not connecting to the server or something else. Traceback shows:

python poster.py -g abty -f "nethecite-test" -c test.conf  /media/sdk1/home/themrsean/test/test.rar 

2012-02-05 08:25:40,670 [INFO] Using yenc-vanilla module for yEnc encoding.
2012-02-05 08:25:41,236 [INFO] Posting 1 article(s)...
^CTraceback (most recent call last):
  File "poster.py", line 146, in <module>
    main()
  File "poster.py", line 141, in main
    generate_par2=options.generate_par2)
  File "/media/sdk1/home/themrsean/madcowfred-newsmangler-e5cd07b/classes/Poster.py", line 154, in post
    _sleep(0.01)

**Comment by john8675309** [comment]
I am just curious if you ever found a resolution to this?  I am having the exact same issue.  I would really like newsmangler to work because of the nzb support.

**Comment by john8675309** [comment]
So it appears that this actually has to do with the particular newhosting provider we're using.  I was using newshosting, I tried astraweb and it worked! So it seems that in 6 years since the release of newsmangler newshosting changes something that made newsmangler not work with it (probably not intentionally).  Just thought I would drop a line and let everyone know, what my fix was.

**Comment by Nethecite** [comment]
Thanks, John. I, too, am using newshosting. The question then becomes, what is newshosting doing differently with their authentication? Newsmangler appears to be waiting for a response that it is not getting, so newshosting is not accepting the request from Newsmangler.

**Comment by madcowfred** [comment]
Can you try updating to current git code and running "python poster.py --debug somedirectory"? The initial connection log entries are useful, eg:

2012-03-08 23:26:06,221 [DEBUG] 0: < 200 NNRP unlimited.newshosting.com Service Ready - support@newshosting.com (fe07.iad)
2012-03-08 23:26:06,221 [DEBUG] 0: > AUTHINFO USER ********
2012-03-08 23:26:06,221 [DEBUG] 1: < 200 NNRP unlimited.newshosting.com Service Ready - support@newshosting.com (fe07.iad)
2012-03-08 23:26:06,221 [DEBUG] 1: > AUTHINFO USER ********
2012-03-08 23:26:06,515 [DEBUG] 0: < 381 PASS required
2012-03-08 23:26:06,515 [DEBUG] 0: > AUTHINFO PASS ********
2012-03-08 23:26:06,515 [DEBUG] 1: < 381 PASS required
2012-03-08 23:26:06,515 [DEBUG] 1: > AUTHINFO PASS ********
2012-03-08 23:26:06,805 [DEBUG] 0: < 281 OK (Posting Allowed)
2012-03-08 23:26:06,805 [DEBUG] 0: ready.
2012-03-08 23:26:06,805 [DEBUG] 1: < 281 OK (Posting Allowed)
2012-03-08 23:26:06,805 [DEBUG] 1: ready.

**Comment by john8675309** [comment]
Hi, here is the output Thanks!!

call1 newsmangler # ./poster.py -c sample.conf --d -f "test please ignore" iso/*
2012-03-08 09:47:13,648 [INFO] Using yenc-vanilla module for yEnc encoding.
2012-03-08 09:47:13,648 [DEBUG] 0: adding FD 3 to poller
2012-03-08 09:47:13,648 [DEBUG] 0: SO_SNDBUF is 262142
2012-03-08 09:47:13,649 [DEBUG] 0: connecting to unlimited.newshosting.com:119
2012-03-08 09:47:13,649 [DEBUG] 1: adding FD 4 to poller
2012-03-08 09:47:13,649 [DEBUG] 1: SO_SNDBUF is 262142
2012-03-08 09:47:13,650 [DEBUG] 1: connecting to unlimited.newshosting.com:119
2012-03-08 09:47:13,711 [DEBUG] 0: connected!
2012-03-08 09:47:13,712 [DEBUG] 1: connected!
2012-03-08 09:47:13,762 [DEBUG] 0: < 200 NNRP unlimited.newshosting.com Service Ready - support@newshosting.com (fed02.iad)
2012-03-08 09:47:13,763 [DEBUG] 0: > AUTHINFO USER ********
2012-03-08 09:47:13,773 [DEBUG] 1: < 200 NNRP unlimited.newshosting.com Service Ready - support@newshosting.com (fed02.iad)
2012-03-08 09:47:13,773 [DEBUG] 1: > AUTHINFO USER ********
2012-03-08 09:47:13,834 [DEBUG] 0: < 381 PASS required
2012-03-08 09:47:13,834 [DEBUG] 0: > AUTHINFO PASS ********
2012-03-08 09:47:13,845 [DEBUG] 1: < 381 PASS required
2012-03-08 09:47:13,845 [DEBUG] 1: > AUTHINFO PASS ********
2012-03-08 09:47:13,906 [DEBUG] 0: < 281 Welcome to NH bro! (Posting Allowed)
2012-03-08 09:47:13,906 [DEBUG] 0: ready.
2012-03-08 09:47:13,906 [INFO] Posting 28 article(s)...
2012-03-08 09:47:13,931 [DEBUG] 0: > POST
2012-03-08 09:47:13,942 [DEBUG] 1: < 281 Welcome to NH bro! (Posting Allowed)
2012-03-08 09:47:13,942 [DEBUG] 1: ready.
2012-03-08 09:47:13,954 [DEBUG] 1: > POST

It just sits on POST, and never does anything.

**Comment by madcowfred** [comment]
That's pretty bizarre, the server should send _some_ kind of response to the POST command. Apparently nothing at all happens with the NewsHosting account I'm testing with, I'll look into this some more :\

**Comment by madcowfred** [comment]
So yeah, apparently we were sending 'POST\n' instead of 'POST\r\n'. Some servers don't enforce the RFC's requirement for \r\n line endings, some do. I've just committed a fix that makes posting work for me on Newshosting :|

**Comment by john8675309** [comment]
It works great!!! Thank you!!
